version: '3.8'

services:
  todoui:
    build: .
    container_name: todoui
    restart: always
    ports:
      - "3040:3040"
    networks:
      - mynetwork3

networks:
  mynetwork3:
    driver: bridge
